### ISSUE TITLE
1.19 Support?

### ISSUE THREAD

**Issue by miditkl** [MasahiroSaito/AllMining#3]
The idea of this project is very nice and I need it for my 1.19 Spigot Server. Since you stopped working on it, I would really appreciate if you continue your work!

Greetings!

**Comment by m4kvn** [comment]
@realSnosh I'll try.

**Comment by m4kvn** [comment]
@realSnosh Please use this new plugin!
- https://www.spigotmc.org/resources/spigot-miner.104088/
- https://github.com/m4kvn/spigot-miner
